 import { Inter } from "next/font/google"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})
 import { AppToaster } from "@/components/ui/toast"
import GlobalNavbar from "@/components/GlobalNavbar"
import Footer from "@/components/Footer"
import PageTransition from "@/components/PageTransition"

import Script from "next/script"
import GoogleAnalyticsTracker from "@/components/GoogleAnalyticsTracker"

import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}');
          `}
        </Script>
      </head>

<body className={inter.className}>
          {/* Google Analytics page view tracker */}
        <GoogleAnalyticsTracker />

        <GlobalNavbar />

        <div className="mx-auto max-w-6xl px-4 md:px-6 pt-10 pb-24">
  {children}
  <div className="p-20 mx-auto mt-10">
  <PageTransition>
    {children}
  </PageTransition>
</div>
</div>

<Footer />

        <AppToaster />
      </body>
    </html>
  )
}
